server:
  port: ${server-port:8911}

spring:
  application:
    name: fms-c-monitor
  boot:
    admin:
      context-path: /monitor

management:
  security:
    enabled: false


eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/